name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=arm64 go build -o dist/scribe-darwin-arm64 ./cmd/scribe
          GOOS=darwin GOARCH=amd64 go build -o dist/scribe-darwin-amd64 ./cmd/scribe
          GOOS=linux GOARCH=amd64 go build -o dist/scribe-linux-amd64 ./cmd/scribe
          GOOS=linux GOARCH=arm64 go build -o dist/scribe-linux-arm64 ./cmd/scribe
          GOOS=windows GOARCH=amd64 go build -o dist/scribe-windows-amd64.exe ./cmd/scribe
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scribe-binaries
          path: dist/*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: scribe-binaries
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


